### ISSUE TITLE
Remove tensorflow from dependencies

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/caliban-toolbox#45]

**Comment by ngreenwald** [comment]
Many of the old i/o functions use tensorflow in order to get channels_first vs channels_last:
https://github.com/vanvalenlab/deepcell-toolbox/blob/baaa9bec4e5c9c7f9a54c1e9f166b9a871868378/deepcell_toolbox/utils/io_utils.py#L100

The current npz-based pipeline doesn't make use of this, but until we've fully migrated over and @geneva-miller isn't using the old version anymore we'll have to keep this

**Comment by willgraf** [comment]
Maybe we can change these utils so that `data_format` is an argument for the function itself (default to `"channels_last"`). That way we can continue to use the data_format logic but can remove the `tf.keras` functions.
