### ISSUE TITLE
consolidate image preprocessing into single notebook

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban-toolbox#56]
As a first step towards figuring out what output file should be generated and put into version control, we need to have a single notebook capable of processing 2D, 3D, and multiplexed data.

**Comment by ngreenwald** [comment]
Hey @MekWarrior @geneva-miller @willgraf, I just pushed what I have so far to the feature/caliban_pipeline branch.

The relevant notebook is here: https://github.com/vanvalenlab/caliban-toolbox/blob/feature/caliban_pipeline/notebooks/Caliban_Figure8_Upload_Combined.ipynb


The general workflow is as follows:

- Load the data from the example_data directory I added. There's an example of 3D, timelapse, and MIBI data. I used the timeseries data for testing out functions since it has multiple channels

-  Run the specified data through the model (not implemented)

- Post-process the model output (not implemented)

- Adjust the contrast of the channels. These are the widgets that Geneva put together. I did some very light refactoring, didn't want to optimize too much before you took a look. The general idea is you pick which channel you want to adjust, adjust it, and save the adjusted output. You can do this for as many channels as you want. 

- Create channel overlays. This allows you to specify any two channels for an overlay. You can create multiple overlays. 

- Select a subset of the raw, adjusted, and overlay channels to be included in the npz. 

- Reshape the resulting array depending on what type of job it is. (Partly implemented)

Remaining todo's are to modify Geneva's old reshaping code, which has a number of possible different output shapes, to work with multichannel 4D arrays, rather than folders of NPZs. Is there any other high-level changes you see? Once Geneva gives this a try, I'll incorporate her changes, and we should have a script that works across different datatypes.

**Comment by ngreenwald** [comment]
I'm almost done refactoring the z/t stack splitting.

Currently, waiting for @geneva-miller to take a look at the image adjustment functionality in the above notebook to see what I've left out, and @MekWarrior to send me the data ontology/brainstorm what requirements we want to enforce for raw input data formats. 

I should be able to submit a PR to merge this all into master on Monday so everyone has a better sense of what the current state of the repository is.

**Comment by geneva-miller** [comment]
I've read through the notebook but have not run it yet. I really like the step you've added after image processing to allow you to process an arbitrary number of channels. 

The main thing that looks like it could be an issue is that when overlaying images, the selected index is carried over from part A (adjusting contrast of single channel). A separate widget step should be included at the start of part B so that the user could completely skip part A if they wanted (perhaps this widget could include a dropdown list to specify channel?). 

Steps in part C may also fail if parts A or B are completely skipped, since `adjusted_channels` and `overlay_channels` are not necessarily initialized.

Overall, I think it's shaping up nicely. I look forward to using it!

**Comment by ngreenwald** [comment]
Awesome! Yeah, the code definitely needs to be hardened, right now highly
context dependent.

The next thing on my to-do list is to refactor the labeling functions you
have written for folders of NPZs. There are a lot of different ones in the
repo, could you point me to the ones that you imagine you'd be
using routinely moving forward?

**Comment by geneva-miller** [comment]
Pretty much all of them except for the "unique" relabeling. I use prediction relabeling before launching 3D data to annotators, relabeling each frame separately is useful after 2D npzs have been reshaped, and I anticipate running the 3D relationship preserving relabeling on output from certain annotation jobs.

That said, I think most of those could be broken down into simpler "relabel array" functions and then, if needed, wrapped in a "relabel npz" or "relabel folder" function. Since we'll be reducing the i/o steps I'm not even sure how necessary a "relabel folder" wrapper will be.
