### ISSUE TITLE
How to deal with distinct save_versions from caliban?

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban-toolbox#67]
Each time the user saves a file, the npz gets a different save_version appended to the end of the NPZ. Does this also happen for browser caliban?

Should we default to loading the npz file with largest save version modifier? Or are we planning on moving away from this?

**Comment by geneva-miller** [comment]
It's a little weird with browser caliban--the code to save a file makes it look like it should get saved with save_version appended. How it works in practice is that the file ends up getting uploaded to output-bucket/subfolder/structure/matching/inputbucket/original_filename.npz, no save_version appended. It's a little bit of a moot point here because browser caliban only allows one file submission (and therefore save + upload step) per file, so multiple versions are not generated.

For desktop caliban, though, any number of save versions can be generated. Our workflow leaves it up to the user to select only the appropriate save version to go into some "curated" folder that is processed further if needed. Perhaps we would want to raise an error if there are multiple save versions of the same file, as it could be ambiguous which is the appropriate one to use (especially in the case of something like filename_save_version_1.npz and filename_save_version_0_save_version_0.npz).

**Comment by ngreenwald** [comment]
Okay, 
So if we want one function that will be able to handle both browser and desktop output, how does this sound?

Check and see if original_filename.npz exists. 
    If yes, load it
    if not, check for original_filename_save_version_x
           if only a single save version, of any version number, load it
           if multiple version numbers, throw an error and ask user to select correct one
    if no matching filename of any kind, print a message and skip without throwing an error

**Comment by geneva-miller** [comment]
I would check for original_filename_save_version_x before loading the original_filename; if we are pulling npzs out of a folder that has multiple save_versions then I think it's likely that the original file was left in as well, and we almost certainly don't want to load that if a modified version exists. So I think "check to see if original_filename exists" would be a special case of checking for different save_versions?

Something like: list all npz files in folder. Pick first one in list, strip out all "save_version"s that may be in filename, check to see if that base filename matches any others in the list. If it does, throw an error. But I guess it depends on if we're getting a predetermined list of npz names to expect (which I think we would want for stitching them back together into a big npz, not as important if we're just concatenating them all together into one big training file with many batches).

**Comment by ngreenwald** [comment]
Got it, sounds good!

Added to #66
